# Generated by Django 4.2.7 on 2025-07-26 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='통화일시')),
                ('call_result', models.CharField(choices=[('connected', '통화성공'), ('no_answer', '부재중'), ('busy', '통화중'), ('wrong_number', '잘못된번호'), ('callback_requested', '재통화요청')], max_length=20, verbose_name='통화결과')),
                ('interest_type', models.CharField(blank=True, choices=[('insurance', '보험'), ('maintenance', '소모품교체'), ('financing', '자동차금융'), ('multiple', '복수관심'), ('none', '관심없음')], max_length=20, null=True, verbose_name='관심분야')),
                ('notes', models.TextField(blank=True, verbose_name='상담내용')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='재통화예정일')),
                ('is_converted', models.BooleanField(default=False, verbose_name='계약성사여부')),
                ('conversion_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='계약성사금액')),
            ],
            options={
                'verbose_name': '통화기록',
                'verbose_name_plural': '통화기록들',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '팀장'), ('agent', '상담원')], default='agent', max_length=20)),
                ('daily_call_target', models.IntegerField(default=100, verbose_name='일일통화목표')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자프로필',
                'verbose_name_plural': '사용자프로필들',
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200)),
                ('total_records', models.IntegerField()),
                ('new_records', models.IntegerField()),
                ('updated_records', models.IntegerField()),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '업로드이력',
                'verbose_name_plural': '업로드이력들',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='고객명')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='휴대전화')),
                ('landline', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('vehicle_number', models.CharField(db_index=True, max_length=20, verbose_name='차량번호')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, verbose_name='차량명')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('vehicle_registration_date', models.DateField(blank=True, null=True, verbose_name='차량등록일')),
                ('chassis_number', models.CharField(blank=True, max_length=50, verbose_name='차대번호')),
                ('inspection_expiry_date', models.DateField(blank=True, null=True, verbose_name='검사만료일')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='보험만기일')),
                ('oil_change_date', models.DateField(blank=True, null=True, verbose_name='오일교환일')),
                ('customer_grade', models.CharField(blank=True, choices=[('vip', 'VIP'), ('regular', '정회원'), ('associate', '준회원'), ('new', '신규'), ('', '등급없음')], max_length=20, verbose_name='고객등급')),
                ('visit_count', models.IntegerField(default=0, verbose_name='방문수')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='소속회사')),
                ('status', models.CharField(choices=[('pending', '미접촉'), ('contacted', '접촉완료'), ('interested', '관심있음'), ('not_interested', '관심없음'), ('callback', '재통화예정'), ('converted', '계약성사'), ('do_not_call', '통화거부')], default='pending', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='우선순위')),
                ('is_inspection_overdue', models.BooleanField(default=False, verbose_name='검사만료')),
                ('is_frequent_visitor', models.BooleanField(default=False, verbose_name='단골고객')),
                ('has_premium_vehicle', models.BooleanField(default=False, verbose_name='프리미엄차량')),
                ('data_source', models.CharField(default='import', max_length=20, verbose_name='데이터출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객들',
                'indexes': [models.Index(fields=['phone', 'vehicle_number'], name='crm_custome_phone_cd14f8_idx'), models.Index(fields=['status'], name='crm_custome_status_d337ab_idx'), models.Index(fields=['inspection_expiry_date'], name='crm_custome_inspect_aa0836_idx'), models.Index(fields=['priority'], name='crm_custome_priorit_350f69_idx'), models.Index(fields=['customer_grade'], name='crm_custome_custome_caa333_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('phone', 'vehicle_number'), name='unique_customer_vehicle'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='상담원'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='crm.customer'),
        ),
    ]
