# Generated by Django 4.2.7 on 2025-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', '활성고객'), ('first_time_lost', '1회차이탈'), ('long_term_lost', '장기이탈'), ('possibly_scrapped', '폐차추정')], default='active', max_length=20, verbose_name='고객상태'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active_customer',
            field=models.BooleanField(default=True, verbose_name='활성고객'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_first_time_no_return',
            field=models.BooleanField(default=False, verbose_name='1회차이탈'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_long_term_absent',
            field=models.BooleanField(default=False, verbose_name='장기이탈'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_happy_call_date',
            field=models.DateField(blank=True, null=True, verbose_name='최근해피콜일'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_inspection_completed',
            field=models.DateField(blank=True, null=True, verbose_name='최근검사완료일'),
        ),
        migrations.AddField(
            model_name='customer',
            name='needs_12month_call',
            field=models.BooleanField(default=False, verbose_name='12개월콜필요'),
        ),
        migrations.AddField(
            model_name='customer',
            name='needs_18month_call',
            field=models.BooleanField(default=False, verbose_name='18개월콜필요'),
        ),
        migrations.AddField(
            model_name='customer',
            name='needs_3month_call',
            field=models.BooleanField(default=False, verbose_name='3개월콜필요'),
        ),
        migrations.AddField(
            model_name='customer',
            name='needs_6month_call',
            field=models.BooleanField(default=False, verbose_name='6개월콜필요'),
        ),
    ]
