# Generated by Django 4.2.7 on 2025-07-27 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_customer_customer_status_customer_is_active_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_call_records', to=settings.AUTH_USER_MODEL, verbose_name='삭제자'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='conversion_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='계약금액'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='계약성사여부'),
        ),
    ]
