# Generated by Django 4.2.7 on 2025-07-27 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_callrecord_deleted_at_callrecord_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(blank=True, choices=[('callback_scheduled', '재통화 예약'), ('visit_scheduled', '방문 예약'), ('quote_sent', '견적 발송'), ('converted', '계약 성사'), ('closed', '종료')], max_length=20)),
                ('notes', models.TextField(verbose_name='후속조치 내용')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='예정일')),
                ('call_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.callrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '후속조치',
                'verbose_name_plural': '후속조치들',
                'ordering': ['created_at'],
            },
        ),
    ]
