# Generated by Django 4.2.7 on 2025-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_callfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='follow_up_completed',
            field=models.BooleanField(default=False, verbose_name='후속조치완료'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='follow_up_notes',
            field=models.TextField(blank=True, verbose_name='후속조치내용'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='requires_follow_up',
            field=models.BooleanField(default=False, verbose_name='후속조치필요'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
