# Generated by Django 4.2.7 on 2025-07-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_callrecord_follow_up_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='parent_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_calls', to='crm.callrecord', verbose_name='원통화기록'),
        ),
    ]
