# Generated by Django 4.2.7 on 2025-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_callrecord_parent_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='do_not_call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='통화금지등록일'),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_call_reason',
            field=models.TextField(blank=True, verbose_name='통화금지사유'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_do_not_call',
            field=models.BooleanField(default=False, verbose_name='통화금지'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_result',
            field=models.CharField(choices=[('connected', '통화성공'), ('no_answer', '부재중'), ('busy', '통화중'), ('wrong_number', '잘못된번호'), ('callback_requested', '재통화요청')], max_length=20, verbose_name='통화상태'),
        ),
    ]
