# Generated by Django 4.2.7 on 2025-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_do_not_call_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='conversion_amount',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='is_converted',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='customer_attitude',
            field=models.CharField(blank=True, choices=[('positive', '긍정적'), ('neutral', '보통'), ('negative', '부정적')], max_length=20, null=True, verbose_name='고객반응'),
        ),
    ]
