# Generated by Django 4.2.7 on 2025-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_callrecord_conversion_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=50, verbose_name='소속팀'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('agent', '상담원'), ('manager', '팀장'), ('admin', '관리자')], default='agent', max_length=20),
        ),
    ]
