# Generated by Django 4.2.7 on 2025-07-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_userprofile_team_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='do_not_call_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='do_not_call_approvals', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_call_approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_call_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='요청일시'),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_call_requested',
            field=models.BooleanField(default=False, verbose_name='통화금지요청중'),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_call_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='do_not_call_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
    ]
