# Generated by Django 4.2.7 on 2025-07-28 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_customer_do_not_call_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='처리기한')),
                ('priority', models.CharField(choices=[('urgent', '긴급'), ('high', '높음'), ('normal', '보통'), ('low', '낮음')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='배정메모')),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_calls', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crm.customer')),
            ],
            options={
                'verbose_name': '콜배정',
                'verbose_name_plural': '콜배정들',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
