# Generated by Django 4.2.7 on 2025-07-28 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_missing_callassignment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': '콜배정', 'verbose_name_plural': '콜배정들'},
        ),
        migrations.RemoveField(
            model_name='callassignment',
            name='assigned_date',
        ),
        migrations.AddField(
            model_name='callassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_column='assigned_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='completed_at', null=True),
        ),
    ]
