# Generated by Django 4.2.7 on 2025-07-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_callassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='actual_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='실제 검사일'),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_extracted_date',
            field=models.DateField(blank=True, null=True, verbose_name='데이터 추출일'),
        ),
    ]
